### ISSUE TITLE
Remove R dependency

### ISSUE THREAD

**Issue by hongfeiyang** [sbmkvp/rta_booking_information#10]
Create status report could be done through Pandas in python, it would be great if the entire thing is done through Python only since most software people may not have R installed and there are a lot of dependencies work to be done just to configure R correctly (`tidyverse` for R compiled 15 minutes on my machine :)

**Comment by sbmkvp** [comment]
Fair! Should I assign this to you? Otherwise I'll try and close other features before working on this.

**Comment by hongfeiyang** [comment]
I will wait till you have a stable version that produces JSON with fixed format

**Comment by sbmkvp** [comment]
Hey, I found a easy way to remove this dependency by just using shell (join command) and jq.

The usage is 

    ./create_status_report.sh docs/centers.json docs/results.json

The changes are committed here 34642eb0e3c1c479b97dc7873266a280c46f2c78
