### ISSUE TITLE
How to run get_all_locations.sh in Windows?

### ISSUE THREAD

**Issue by arvz** [sbmkvp/rta_booking_information#14]
I've gotten it all mostly running now, I can scrape data on single location using srape_availability.py, but how would I go about running the sh script in Windows?

**Comment by hongfeiyang** [comment]
> I've gotten it all mostly running now, I can scrape data on single location using srape_availability.py, but how would I go about running the sh script in Windows? 

Install bash like terminals like mingw or git bash

**Comment by sbmkvp** [comment]
To add to the discussion, we also need to install gnuparallel, jq and git for this bash script to work. Assuming that one is using git bash to run this shell script parallel and jq installation are discussed on SO below,

 1. Installing gnuparalle - https://stackoverflow.com/questions/52393850/how-to-install-gnu-parallel-on-windows-10-using-git-bash 
 2. Installing jq - https://stackoverflow.com/questions/53967693/how-to-run-jq-from-gitbash-in-windows 

I'll add this to documentation when I get time.

**Comment by sbmkvp** [comment]
documentation added in a7016e307f9e6d65f5822f8a23716e9b614cced5
