### ISSUE TITLE
Expanded Details

### ISSUE THREAD

**Issue by madhav-mk** [sbmkvp/rta_booking_information#17]
Is it possible to see all available bookings at a particular centre by clicking on it, instead of just the earliest available?

**Comment by sbmkvp** [comment]
The information need to implement is  available in the results.json file. It just needs to be included in the front-end. I am open to a pull request if anyone want to work on this feature.

**Comment by sbmkvp** [comment]
implemented in 189064647f7b91e2e41fd3188f14ad7c1aea3ef5
